apiVersion: v1
data:      
    CAMUNDA_LICENSE_KEY: ZGVtbw==
kind: Secret
metadata:
  name: camunda-camunda-platform-license
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: camunda-operate-identity-secret
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  operate-secret: "Demo"

---
apiVersion: v1
kind: Secret
metadata:
  name: camunda-tasklist-identity-secret
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  tasklist-secret: "Demo"

---
apiVersion: v1
kind: Secret
metadata:
  name: camunda-optimize-identity-secret
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  optimize-secret: "Demo"

---
apiVersion: v1
kind: Secret
metadata:
  name: camunda-connectors-identity-secret
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  connectors-secret: "Demo"

---
apiVersion: v1
kind: Secret
metadata:
  name: camunda-zeebe-identity-secret
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  zeebe-secret: "Demo"

---
apiVersion: v1
kind: Secret
metadata:
  name: camunda-keycloak
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  admin-password: "Demo"
  password: "Demo"
  user: "Demo"
  identity-keycloak-postgresql-user-password: "Demo"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-password
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  smtp-password: "Demo"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  admin-password: "Demo"
  admin-user: "Demo"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: camunda-web-modeler-restapi
  namespace: camunda-platform
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda-platform
type: Opaque
stringData:
  database-password: "Demo"